notifications:
  email: false
sudo: false
language: ruby
rvm:
  - 2.2.2
before_install:
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xjf phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - mkdir -p /home/travis/bin
  - mv phantomjs /home/travis/bin
  - "export PATH=/home/travis/bin:$PATH"
before_script:
  - "mysql -e 'create database europeana_channels_blacklight_test;'"
  - "cp -r ./deploy/travis/. ."
env:
  - RAILS_ENV=test
