default: &default
  storage: :fog
  fog_credentials:
    provider: AWS
    aws_access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
    aws_secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
    region: <%= ENV['S3_REGION'] %>
    host: <%= ENV['S3_HOST'] %>
    endpoint: <%= ENV['S3_ENDPOINT'] %>
    path_style: <%= ENV['S3_PATH_STYLE'].to_i == 1 %>
  fog_directory: <%= ENV['S3_BUCKET'] %>
  fog_host: <%= ENV['S3_PUBLIC_URL'].present? ? ENV['S3_PUBLIC_URL'] : "#{ENV['S3_ENDPOINT']}/#{ENV['S3_BUCKET']}" %>
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
