<%
if ENV.key?('VCAP_SERVICES')
  services = JSON.parse(ENV['VCAP_SERVICES'])
  pg_config = services['compose-for-postgresql']
end
fail 'No PostgreSQL service found in environment.' if pg_config.nil?
service_config = pg_config.first
pg_url = service_config['credentials']['uri']
%>
production:
  url: "<%= pg_url %>"
