# See https://docs.newrelic.com/docs/agents/ruby-agent/configuration/ruby-agent-configuration#browser_monitoring
common: &default_settings
  license_key: '<%= JSON.parse(ENV["VCAP_SERVICES"])["user-provided"].detect { |up| up["name"] == "newrelic" }["credentials"]["licenseKey"] %>'
  agent_enabled: true
  app_name: '<%= JSON.parse(ENV["VCAP_APPLICATION"])["application_name"] %>'
  log_level: info
  browser_monitoring:
    auto_instrument: false
  audit_log:
    enabled: false
  capture_params: false
  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500
  error_collector:
    enabled: true
    ignore_errors: "ActionController::RoutingError,Sinatra::NotFound"
development:
  <<: *default_settings
  monitor_mode: false
  developer_mode: true
test:
  <<: *default_settings
  monitor_mode: false
production:
  <<: *default_settings
  monitor_mode: true
